FROM python:3-alpine3.20

ENV ROTATE_CRON=""
ENV ROTATE_OPTIONS=""
ENV ROTATE_ADDITIONAL_OPTIONS=""
ENV ROTATE_PATH1=""
ENV ROTATE_PATH2=""
ENV ROTATE_PATH3=""
ENV ROTATE_PATH4=""
ENV ROTATE_PATH5=""
ENV ROTATE_PATH6=""
ENV ROTATE_PATH7=""
ENV ROTATE_PATH8=""
ENV ROTATE_PATH9=""
ENV ROTATE_PATH10=""

RUN pip install rotate-backups

#RUN mkdir /data

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["sh", "/entrypoint.sh"]

CMD ["crond", "-f", "-l", "0"]
